name: publish docs

on:
  push:
    branches:
      - main
    tags:
      - v3.*

permissions:
  contents: read

jobs:
  test-docs:
    name: test-docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Set PATH
        run: echo "${GITHUB_WORKSPACE}/.local/bin" >>"${GITHUB_PATH}"

      - run: make ensure-gfmrun

      - run: make gfmrun
        env:
            FLAGS: --walk docs/v3/

      - run: make diffcheck

  publish:
    permissions:
        contents: write
    if: startswith(github.ref, 'refs/tags/')
    name: publish
    needs: [test-docs]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create virtual environment
        run: |
          python -m venv venv
          
      - run: |
          . venv/bin/activate          
          make ensure-mkdocs
        env:
          FLAGS: --upgrade-pip

      - run: make set-mkdocs-remote
        env:
          MKDOCS_REMOTE_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          . venv/bin/activate          
          make deploy-mkdocs
        